################ Dutch language ##################
[nl]
languageName = "NL"
languageCode = "nl-nl"
weight = 1
################ English language ##################
[en]
languageName = "EN"
languageCode = "en-us"
weight = 2
