############# Dutch navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Over"
url = "over/"
weight = 2

# footer menu
[[footer]]
name = "De Organisatie"
url = "overnew/organisatie/"
weight = 1

[[footer]]
name = "ARB"
url = "https://amsterdamscheroeibond.nl/"
weight = 2

[[footer]]
name = "Willem III"
url = "https://www.willem3.nl/"
weight = 3
