############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

# footer menu
[[footer]]
name = "ARB"
url = "https://amsterdamscheroeibond.nl/"
weight = 2

[[footer]]
name = "Willem III"
url = "https://www.willem3.nl/"
weight = 3
